const Chapter1 = {
  'Greetings & Basics': {
    'What is "Hello"?': ['hola'],
    'What is "What is your name? (formal)"?': ['¿cómo se llama usted?', '¿qué es su nombre?'],
    'What is "What is your name? (informal)"?': ['¿cómo te llamas?', '¿qué es tu nombre?'],
    'What is "My name is..."?': ['me llamo...'],
    'What is "And you? (formal)"?': ['¿y usted?'],
    'What is "And you? (informal)"?': ['¿y tú?'],
    'What is "It\'s a pleasure/Nice to meet you"?': ['mucho gusto'],
    'What is "The pleasure is mine."?': ['el gusto es mío.'],
    'What is "name"?': ['el nombre'],
    'What is "Mr."?': ['el señor'],
    'What is "Ms., Mrs."?': ['la señora'],
    'What is "Delighted/Pleased to meet you"?': ['encantado'],
    'What is "Likewise"?': ['igualmente'],
    'What is "good morning"?': ['buenos días'],
    'What is "good afternoon"?': ['buenas tardes'],
    'What is "good evening / good night"?': ['buenas noches'],
    'What is "goodbye"?': ['adiós'],
    'What is "bye"?': ['chau'],
    'What is "How are you? (formal)"?': ['¿cómo está usted?'],
    'What is "How are you? (informal)"?': ['¿cómo estás?'],
    'What is "What\'s up? / How\'s it going?"?': ['¿qué tal?'],
    'What is "What\'s new?"?': ['¿qué hay de nuevo?'],
    'What is "well"?': ['bien'],
    'What is "very well"?': ['muy bien'],
    'What is "bad"?': ['mal'],
    'What is "nothing"?': ['nada'],
    'What is "so-so"?': ['regular'],
    'What is "thank you"?': ['gracias']
  },
  'Origin & Nationality': {
    'What is "I am from"?': ['soy de'],
    'What is "Where are you from? (informal)"?': ['¿de dónde eres?'],
    'What is "Where are you from? (formal)"?': ['¿de dónde es usted?'],
    'What is "flag"?': ['la bandera'],
    'What is "capital city"?': ['la capital'],
    'What is "nationality"?': ['la nacionalidad'],
    'What is "country"?': ['el país'],
    'What is "The United States of America"?': ['los estados unidos de américa', 'los estados unidos', 'los e.e.u.u']
  },
  'Numbers': {
    'What is "one"?': ['uno'],
    'What is "2 (two)"?': ['dos'],
    'What is "three"?': ['tres'],
    'What is "four"?': ['cuatro'],
    'What is "five"?': ['cinco'],
    'What is "six"?': ['seis'],
    'What is "seven"?': ['siete'],
    'What is "eight"?': ['ocho'],
    'What is "nine"?': ['nueve'],
    'What is "ten"?': ['diez'],
    'What is "eleven"?': ['once'],
    'What is "twelve"?': ['doce'],
    'What is "thirteen"?': ['trece'],
    'What is "fourteen"?': ['catorce'],
    'What is "fifteen"?': ['quince'],
    'What is "sixteen"?': ['dieciséis', 'diez y seis'],
    'What is "seventeen"?': ['diecisiete', 'diez y siete'],
    'What is "eighteen"?': ['dieciocho', 'diez y ocho'],
    'What is "nineteen"?': ['diecinueve', 'diez y nueve'],
    'What is "twenty"?': ['veinte'],
    'What is "twenty-one"?': ['veintiuno', 'veinte y uno'],
    'What is "twenty-two"?': ['veintidós', 'veinte y dos'],
    'What is "twenty-three"?': ['veintitrés', 'veinte y tres'],
    'What is "twenty-four"?': ['veinticuatro', 'veinte y cuatro'],
    'What is "twenty-five"?': ['veinticinco', 'veinte y cinco'],
    'What is "twenty-six"?': ['veintiséis', 'veinte y seis'],
    'What is "twenty-seven"?': ['veintisiete', 'veinte y siete'],
    'What is "twenty eight"?': ['veintiocho', 'veinte y ocho'],
    'What is "twenty-nine"?': ['veintinueve', 'veinte y nueve'],
    'What is "thirty"?': ['treinta']
  },
  'School & Classroom': {
    'What is "teacher" (male)?': ['el profesor'],
    'What is "teacher" (female)?': ['la profesora'],
    'What is "clock"?': ['el reloj'],
    'What is "students"?': ['los estudiantes'],
    'What is "book"?': ['el libro'],
    'What is "blackboard/whiteboard"?': ['la pizarra'],
    'What is "backpack"?': ['la mochila'],
    'What is "student desk"?': ['el pupitre'],
    'What is "chair"?': ['la silla'],
    'What is "teacher\'s desk"?': ['el escritorio'],
    'What is "computer"?': ['la computadora'],
    'What is "pencil"?': ['el lápiz'],
    'What is "notebook"?': ['el cuaderno'],
    'What is "pen"?': ['la pluma'],
    'What is "homework"?': ['la tarea'],
    'What is "lunch"?': ['el almuerzo']
  },
  'School Subjects': {
    'What is "subjects"?': ['las materias'],
    'What is "art"?': ['el arte'],
    'What is "science"?': ['las ciencias'],
    'What is "Spanish"?': ['el español'],
    'What is "geography"?': ['la geografía'],
    'What is "history"?': ['la historia'],
    'What is "English"?': ['el inglés'],
    'What is "math"?': ['las matemáticas'],
    'What is "music"?': ['la música']
  },
  'Classroom Phrases': {
    'What is "How do you say... en español?"?': ['¿cómo se dice... en español?'],
    'What is "excuse me"?': ['con permiso'],
    'What is "You\'re welcome"?': ['de nada'],
    'What is "really?"?': ['¿de veras?'],
    'What is "What page are we on?"?': ['¿en qué página estamos?'],
    'What is "More slowly, please"?': ['más despacio, por favor'],
    'What is "Thank you very much"?': ['muchas gracias'],
    'What is "I don\'t understand"?': ['no entiendo'],
    'What is "I don\'t know"?': ['no sé'],
    'What is "please"?': ['por favor'],
    'What is "What does ... mean?"?': ['¿qué significa...?'],
    'What is "I have a question"?': ['tengo una pregunta']
  },
  'Miscellaneous Basics': {
    'What is "girl"?': ['la chica'],
    'What is "boy"?': ['el chico'],
    'What is "Which is...?"?': ['¿cuál es...?'],
    'What is "How many? (for male/mixed groups)"?': ['¿cuántos?'],
    'What is "How many? (for all-female groups)"?': ['¿cuántas?'],
    'What is "I study"?': ['estudio'],
    'What is "you study (informal)"?': ['estudias'],
    'What is "week"?': ['la semana'],
    'What is "yesterday"?': ['ayer'],
    'What is "my"(singular)?': ['mi'],
    'What is "there is, there are"?': ['hay']
  }
};
const Chapter2 = {
  'Classroom People & Objects': {
    'What is "student" (male)?': ['el estudiante'],
    'What is "student" (female)?': ['la estudiante'],
    'What is "teacher" (male)?': ['el profesor'],
    'What is "teacher" (female)?': ['la profesora'],
    'What is "eraser"?': ['el borrador'],
    'What is "desk"?': ['el escritorio'],
    'What is "book"?': ['el libro'],
    'What is "map"?': ['el mapa'],
    'What is "table"?': ['la mesa'],
    'What is "backpack"?': ['la mochila'],
    'What is "paper"?': ['el papel'],
    'What is "wastebasket"?': ['la papelera'],
    'What is "blackboard"?': ['la pizarra'],
    'What is "pen"?': ['la pluma', 'el bolígrafo'],
    'What is "door"?': ['la puerta'],
    'What is "clock/watch"?': ['el reloj'],
    'What is "seat"?': ['la silla'],
    'What is "chalk"?': ['la tiza'],
    'What is "window"?': ['la ventana'],
    'What is "school"?': ['la escuela']
  },
  'Campus Locations': {
    'What is "library"?': ['la biblioteca'],
    'What is "cafeteria"?': ['la cafetería'],
    'What is "house/home"?': ['la casa'],
    'What is "stadium"?': ['el estadio'],
    'What is "laboratory"?': ['el laboratorio'],
    'What is "bookstore"?': ['la librería'],
    'What is "university/college"?': ['la universidad']
  },
  'School & Schedule': {
    'What is "class"?': ['la clase'],
    'What is "course"?': ['el curso'],
    'What is "test/exam"?': ['el examen'],
    'What is "schedule"?': ['el horario'],
    'What is "quiz"?': ['la prueba'],
    'What is "semester"?': ['el semestre'],
    'What is "homework"?': ['la tarea'],
    'What is "trimester"?': ['el trimestre'],
    'What is "lunch"?': ['el almuerzo']
  },
  'Subject Pronouns': {
    'What is "I"?': ['yo'],
    'What is "you (informal)"?': ['tú'],
    'What is "he"?': ['él'],
    'What is "she"?': ['ella'],
    'What is "you (formal)"?': ['usted'],
    'What is "we (male/mixed group)"?': ['nosotros'],
    'What is "we (all-female group)"?': ['nosotras'],
    'What is "you all (Spain, male/mixed group)"?': ['vosotros'],
    'What is "you all (Spain, all-female group)"?': ['vosotras'],
    'What is "they (male/mixed group)"?': ['ellos'],
    'What is "they (all-female group)"?': ['ellas'],
    'What is "you all"?': ['ustedes']
  },
  'Academic Subjects': {
    'What is "art"?': ['el arte'],
    'What is "biology"?': ['la biología'],
    'What is "sciences"?': ['las ciencias'],
    'What is "computer science"?': ['la computación'],
    'What is "accounting"?': ['la contabilidad'],
    'What is "economics"?': ['la economía'],
    'What is "Spanish"?': ['el español'],
    'What is "physics"?': ['la física'],
    'What is "geography"?': ['la geografía'],
    'What is "history"?': ['la historia'],
    'What is "humanities"?': ['las humanidades'],
    'What is "English"?': ['el inglés'],
    'What is "foreign languages"?': ['las lenguas extranjeras'],
    'What is "literature"?': ['la literatura'],
    'What is "mathematics"?': ['las matemáticas'],
    'What is "music"?': ['la música'],
    'What is "journalism"?': ['el periodismo'],
    'What is "psychology"?': ['la psicología'],
    'What is "chemistry"?': ['la química'],
    'What is "sociology"?': ['la sociología'],
    'What is "physical education class"?': ['la educación física']
  },
  'Interrogatives & Conjunctions': {
    'What is "where to?"?': ['¿adónde?'],
    'What is "which one?"?': ['¿cuál?'],
    'What is "which ones?"?': ['¿cuáles?'],
    'What is "why?"?': ['¿por qué?'],
    'What is "because"?': ['porque']
  },
  'AR Verbs': {
    'What is "to dance"?': ['bailar'],
    'What is "to look for"?': ['buscar'],
    'What is "to walk"?': ['caminar'],
    'What is "to sing"?': ['cantar'],
    'What is "to have dinner"?': ['cenar'],
    'What is "to buy"?': ['comprar'],
    'What is "to answer"?': ['contestar'],
    'What is "to converse/chat"?': ['conversar'],
    'What is "to have breakfast"?': ['desayunar'],
    'What is "to rest"?': ['descansar'],
    'What is "to wish/desire"?': ['desear'],
    'What is "to draw"?': ['dibujar'],
    'What is "to teach"?': ['enseñar'],
    'What is "to listen"?': ['escuchar'],
    'What is "to wait for to hope"?': ['esperar'],
    'What is "to study"?': ['estudiar'],
    //'What is "to explain"?': ['explicar'],
    'What is "to like"?': ['gustar'],
    'What is "to talk/to speak"?': ['hablar'],
    'What is "to arrive"?': ['llegar'],
    'What is "to carry"?': ['llevar'],
    'What is "to look (at)/watch"?': ['mirar'],
    'What is "to need"?': ['necesitar'],
    'What is "to practice"?': ['practicar'],
    'What is "to ask (a question)"?': ['preguntar'],
    'What is "to prepare"?': ['preparar'],
    'What is "to return"?': ['regresar'],
    'What is "to end/finish"?': ['terminar'],
    'What is "to take/drink"?': ['tomar'],
    'What is "to work"?': ['trabajar'],
    'What is "to travel"?': ['viajar']
  },
  'Prepositions & Locations': {
    'What is "to the right of"?': ['a la derecha de'],
    'What is "to the left of"?': ['a la izquierda de'],
    'What is "in, on"?': ['en'],
    'What is "near"?': ['cerca de'],
    'What is "with"?': ['con'],
    'What is "below"?': ['debajo de'],
    'What is "in front of"?': ['delante de'],
    'What is "behind"?': ['detrás de'],
    'What is "on top of"?': ['encima de'],
    'What is "between"?': ['entre'],
    'What is "far from"?': ['lejos de'],
    'What is "without"?': ['sin'],
    'What is "over, about"?': ['sobre'],
    'What is "next to"?"': ['al lado de']
  },
  'Calendar & Days': {
    'What is "when"?': ['¿cuándo?'],
    'What is "What day is today?"?': ['¿qué día es hoy?'],
    'What is "What is the date?"?': ['¿cuál es la fecha?'],
    'What is "Today is. ."?': ['hoy es...'],
    'What is "week"?': ['la semana'],
    'What is "Monday"?': ['lunes'],
    'What is "Tuesday"?': ['martes'],
    'What is "Wednesday"?': ['miércoles'],
    'What is "Thursday"?': ['jueves'],
    'What is "Friday"?': ['viernes'],
    'What is "Saturday"?': ['sábado'],
    'What is "Sunday"?': ['domingo']
  }
};
const Chapter3 = {
  'Family Members': {
    'What is "grandfather"?': ['el abuelo'],
    'What is "grandmother"?': ['la abuela'],
    'What is "grandparents"?': ['los abuelos'],
    'What is "great-grandfather"?': ['el bisabuelo'],
    'What is "great-grandmother"?': ['la bisabuela'],
    'What is "brother-in-law"?': ['el cuñado'],
    'What is "sister-in-law"?': ['la cuñada'],
    'What is "husband"?': ['el esposo'],
    'What is "wife"?': ['la esposa'],
    'What is "family"?': ['la familia'],
    'What is "brother"?': ['el hermano'],
    'What is "sister"?': ['la hermana'],
    'What is "stepmother"?': ['la madrastra'],
    'What is "mother"?': ['la madre'],
    'What is "stepfather"?': ['el padrastro'],
    'What is "father"?': ['el padre'],
    'What is "parents"?': ['los padres'],
    'What is "relatives"?': ['los parientes'],
    'What is "nephew"?': ['el sobrino'],
    'What is "niece"?': ['la sobrina'],
    'What is "father-in-law"?': ['el suegro'],
    'What is "mother-in-law"?': ['la suegra'],
    'What is "uncle"?': ['el tío'],
    'What is "aunt"?': ['la tía'],
    'What is "son-in-law"?': ['el yerno'],
    'What is "daughter-in-law"?': ['la nuera'],
    'What is "uncles and aunts"?': ['los tíos'],
    'What is "cousins"?': ['los primos']
  },
  'People & Relationships': {
    'What is "friend" (male)?': ['el amigo'],
    'What is "friend" (female)?': ['la amiga'],
    'What is "people"?': ['la gente'],
    'What is "person"?': ['la persona'],
    'What is "last name"?': ['el apellido']
  },
  'Professions': {
    'What is "artist" (male)?': ['el artista'],
    'What is "artist" (female)?': ['la artista'],
    'What is "doctor" (male)?': ['el médico', 'el doctor'],
    'What is "doctor"? (female)': ['la médica', 'la doctora'],
    'What is "engineer" (male)?': ['el ingeniero'],
    'What is "engineer" (female)?': ['la ingeniera'],
    'What is "journalist" (male)?': ['el periodista'],
    'What is "journalist" (female)?': ['la periodista'],
    'What is "computer programmer" (male)?': ['el programador'],
    'What is "computer programmer" (female)?': ['la programadora']
  },
  'ER/IR Verbs': {
    'What is "to have"?': ['tener'],
    'What is "to come"?': ['venir'],
    'What is "to learn"?': ['aprender'],
    'What is "to drink"?': ['beber'],
    'What is "to describe"?': ['describir'],
    'What is "to eat"?': ['comer'],
    'What is "to understand"?': ['comprender'],
    'What is "to run"?': ['correr'],
    'What is "to believe in"?': ['creer (en)'],
    'What is "should / must"?': ['deber'],
    'What is "to write"?': ['escribir'],
    'What is "to leer"?': ['leer'],
    'What is "to receive"?': ['recibir'],
    'What is "to live"?': ['vivir']
  },
  'Descriptive Adjectives': {
    'What is "tall" (masculine singular)?': ['alto'],
    'What is "short" (feminine singular)?': ['baja'],
    'What is "nice; friendly" (masculine plural)?': ['simpáticos'],
    'What is "good" (feminine singular)?': ['buena'],
    'What is "intelligent" (singular form)?': ['inteligente'],
    'What is "hard-working" (feminine singular)?': ['trabajadora'],
    'What is "important" (singular form)?': ['importante'],
    'What is "interesting" (singular form)?': ['interesante'],
    'What is "easy" (singular form)?': ['fácil'],
    'What is "difficult" (singular form)?': ['difícil'],
    'What is "same" (masculine plural)?': ['mismos']
  },
  'Nationalities': {    

    'What is "German" (feminine plural)?': ['alemanas'],
    'What is "Argentine" (masculine plural)?': ['argentinos'],
    'What is "Canadian" (singular form)?': ['canadiense'],
    'What is "Chinese" (masculine plural)?': ['chinos'],
    'What is "Costa Rican" (singular form)?': ['costarricense'],
    'What is "Cuban" (masculine singular)?': ['cubano'],
    'What is "Ecuadorian" (feminine singular)?': ['ecuatoriana'],
    'What is "Spanish" (feminine plural)?': ['españolas'],
    'What is "from the U.S." (singular form)?': ['estadounidense'],
    'What is "French" (singular form)?': ['francés'],
    'What is "English" (singular form)?': ['inglés'],
    'What is "Italian" (masculine plural)?': ['italianos'],
    'What is "Japanese" (masculine plural)?': ['japoneses'],
    'What is "Mexican" (masculine singular)?': ['mexicano'],
    'What is "North American" (feminine singular)?': ['norteamericana'],
    'What is "Puerto Rican" (feminine plural)?': ['puertorriqueñas'],
    'What is "Russian" (masculine plural)?': ['rusos']
  }
};
const data = {
    "Spanish 1A":{
        "Lecciones Preliminar & 1":Chapter1,
        "Lección 2":Chapter2,
        "Lección 3":Chapter3
    }
}
const correctFeedback = [
  "Spot on!",
  "You nailed it!",
  "Absolutely right!",
  "Brilliant answer!",
  "You're on a roll!",
  "Perfect match!",
  "Way to go!",
  "Genius move!",
  "Superb choice!",
  "Awesome job!",
  "You make this look easy!",
  "Fantastic work!",
  "Incredible job!",
  "You are crushing this!",
  "Outstanding choice!",
  "Magnificent response!",
  "Top tier answer!",
  "Phenomenal effort!",
  "Perfect execution!",
  "Masterful thinking!",
  "Unstoppable energy!",
  "Sensational work!",
  "Bingo!",
  "Exactly right!",
  "You hit the bullseye!",
  "Pure genius!",
  "Remarkable answer!",
  "You've got skills!",
  "Spectacular work!",
  "Flawless reasoning!",
  "Inspirational stuff!",
  "You're unstoppable!",
  "Superb accuracy!",
  "Legendary performance!",
  "Splendid determination!",
  "You are on fire!",
  "Top notch response!",
  "You know your stuff!",
  "Utterly correct!",
  "First class thinking!",
  "A perfect result!",
  "You're mastering this!",
  "Exemplary effort!",
  "Outstanding knowledge!",
  "Brilliant clarity!",
  "You've got this down!",
  "Tremendous job!",
  "Simply superb!"
];
const incorrectFeedback = [
    "Oops!",
    "Try again.",
    "Better luck next time!",
    "Not quite.",
    "Everyone makes mistakes.",
    "Getting closer!",
    "You're getting better!",
    "Every mistake is an opportunity to learn.",
    "You can do this!",
    "You'll get it next time!",
    "You can do better!",
    "You're improving!",
    "We all make mistakes sometimes.",
    "So close!",
    "Nice try!",
    "Keep going!",
    "Great effort!",
    "Keep pushing!",
    "Almost!",
    "Stay focused and you will do it!",
    "Let's retry that.",
    "Just missed it.",
    "Practice makes perfect!",
    "Step by step, you WILL do it!",
    "Failure is just feedback.",
    "You're on your way to perfection!",
    "It happens.",
    "Just a minor setback.",
    "No pressure.",
];
// JavaScript Array for Streak Losses
//Currently just using one
const streakLossFeedback = [
    "You've lost your streak.",
    "Streak lost!",
    "You can build another streak.",
    "That was an epic streak while it lasted!",
    "Streak reset, let's rebuild!",
    "Streak over. Ready for the next one?",
    "Bye bye streak!",
    "Lost the streak, but you're still learning.",
    "Beat your lost streak this time!",
];